apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysql-namespace
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 318623136204.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:mysql-v0.1
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    - name: MYSQL_DATABASE
      value: employees
    ports:
    - containerPort: 3306
  imagePullSecrets:
    - name: my-ecr-secret
