apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
       - name: my-ecr-secret
      containers:
      - name: webapp
        image: 318623136204.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:webapp-v0.2
        env:
        - name: DBHOST
          value: mysql-service.mysql-namespace.svc.cluster.local
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
        - name: DATABASE
          value: employees
        - name: APP_COLOR
          value: blue
        ports:
        - containerPort: 8080
