apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: webapp-namespace
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: 318623136204.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:webapp-v0.1
    env:
    - name: DBHOST
      value: mysql-service.mysql-namespace.svc.cluster.local
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: root
    - name: DBPWD
      value: pw
    - name: DATABASE
      value: employees
    - name: APP_COLOR
      value: blue
    ports:
    - containerPort: 8080
  imagePullSecrets:
    - name: my-ecr-secret

